name: tensorflow-object-detection-house-nadir
channels:
- scw
- conda-forge
- esri
- defaults
dependencies:
- arrow=0.12.1=py36_1002
- binaryornot=0.4.4=py_1
- click=7.0=py_0
- cookiecutter=1.6.0=py36_1000
- cryptography=2.3.1=py36h74b6da3_0
- cryptography-vectors=2.3.1=py36_1000
- freetype=2.8.1=vc14_0
- geos=3.6.2=he025d50_3
- jinja2-time=0.2.0=py_2
- libpng=1.6.34=vc14_0
- libsodium=1.0.16=vc14_0
- openssl=1.0.2o=vc14_0
- poyo=0.4.2=py_0
- shapely=1.6.4=py36hc90234e_1000
- whichcraft=0.5.2=py_1
- zeromq=4.2.5=vc14_2
- zlib=1.2.11=vc14_0
- asn1crypto=0.24.0=py36_0
- atomicwrites=1.2.1=py36_0
- attrs=18.2.0=py36h28b3542_0
- backcall=0.1.0=py36_0
- blas=1.0=mkl
- bleach=2.1.4=py36_0
- ca-certificates=2018.03.07=0
- certifi=2018.8.24=py36_1
- cffi=1.11.5=py36h74b6da3_1
- cftime=1.0.0b1=py36h452e1ab_0
- chardet=3.0.4=py36_1
- colorama=0.3.9=py36h029ae33_0
- cycler=0.10.0=py36h009560c_0
- decorator=4.3.0=py36_0
- entrypoints=0.2.3=py36_2
- et_xmlfile=1.0.1=py36h3d2d736_0
- fastcache=1.0.2=py36hfa6e2cd_2
- html5lib=1.0.1=py36_0
- idna=2.7=py36_0
- ipykernel=4.9.0=py36_0
- ipython=6.5.0=py36_0
- ipython_genutils=0.2.0=py36h3c5d0ee_0
- ipywidgets=7.4.1=py36_0
- jdcal=1.4=py36_0
- jinja2=2.10=py36_0
- jsonschema=2.6.0=py36h7636477_0
- jupyter_client=5.2.3=py36_0
- jupyter_console=5.2.0=py36_1
- jupyter_core=4.4.0=py36_0
- jupyterlab=0.34.7=py36_0
- jupyterlab_launcher=0.13.1=py36_0
- kiwisolver=1.0.1=py36h6538335_0
- markupsafe=1.0=py36hfa6e2cd_1
- mistune=0.8.3=py36hfa6e2cd_1
- mkl_fft=1.0.4=py36h1e22a9b_1
- mkl_random=1.0.1=py36h77b88f5_1
- more-itertools=4.3.0=py36_0
- mpmath=1.0.0=py36_2
- nbformat=4.4.0=py36h3a5bc1b_0
- nose=1.3.7=py36_2
- notebook=5.6.0=py36_0
- numexpr=2.6.8=py36h9ef55f4_0
- numpy=1.15.1=py36ha559c80_0
- numpy-base=1.15.1=py36h8128ebf_0
- openpyxl=2.5.6=py36_0
- pandas=0.23.4=py36h830ac7b_0
- pandocfilters=1.4.2=py36_1
- parso=0.3.1=py36_0
- pickleshare=0.7.4=py36h9de030f_0
- pip=10.0.1=py36_0
- pluggy=0.7.1=py36h28b3542_0
- prompt_toolkit=1.0.15=py36h60b8f86_0
- py=1.6.0=py36_0
- pycparser=2.18=py36_1
- pygments=2.2.0=py36hb010967_0
- pyopenssl=18.0.0=py36_0
- pyparsing=2.2.0=py36_1
- pysocks=1.6.8=py36_0
- pytest=3.7.4=py36_0
- python=3.6.6=hea74fb7_0
- python-dateutil=2.7.3=py36_0
- pyzmq=17.1.2=py36hfa6e2cd_0
- requests=2.19.1=py36_0
- scipy=1.1.0=py36h4f6bf74_1
- send2trash=1.5.0=py36_0
- setuptools=40.2.0=py36_0
- simplegeneric=0.8.1=py36_2
- six=1.11.0=py36_1
- terminado=0.8.1=py36_1
- testpath=0.3.1=py36h2698cfe_0
- tornado=5.1=py36hfa6e2cd_0
- traitlets=4.3.2=py36h096827d_0
- urllib3=1.23=py36_0
- vc=14=h0510ff6_3
- wcwidth=0.1.7=py36h3d5aa90_0
- webencodings=0.5.1=py36_1
- wheel=0.31.1=py36_0
- widgetsnbextension=3.4.1=py36_0
- win_inet_pton=1.0.1=py36_1
- wincertstore=0.2=py36h7fe50ca_0
- winkerberos=0.7.0=py36_1
- winpty=0.4.3=4
- xlrd=1.1.0=py36_1
- xlwt=1.3.0=py36h1a4751e_0
- arcgis=1.5.0=py36_0
- arcgispro=2.3=h35c310c_0
- future=0.16.0=py36_1
- h5py=2.8.0=py36_arcgispro_4
- icc_rt=2018.0.2=arcgispro_0
- intel-openmp=2018.0.3=arcgispro_0
- jedi=0.12.1=py36_0
- keyring=13.2.1=py36_0
- matplotlib=2.2.3=py36_0e
- mkl=2018.0.3=arcgispro_0
- nbconvert=5.3.1=py36_0
- netcdf4=1.4.1=py36_arcgispro_3
- prometheus_client=0.3.1=py36_0
- pypdf2=1.26.0=py_2
- pytz=2018.5=py36_0
- pywin32-ctypes=0.2.0=py36_0
- pywinpty=0.5=py36_0
- sympy=1.2=py36_0
- vs2015_runtime=14.0.25420=0
- gdal=2.1.1=arcgispro_0
- pip:
  - et-xmlfile==1.0.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.3
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - jupyterlab-launcher==0.13.1
  - mkl-fft==1.0.4
  - mkl-random==1.0.1
  - prometheus-client==0.3.1
  - prompt-toolkit==1.0.15
  - win-inet-pton==1.0.1

